name: football

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: 'stable'
      flutter_version: '3.24.0'
      setup: |
        flutter pub run build_runner build --delete-conflicting-outputs
        dart format --line-length 80 lib test
      coverage_excludes: '**/*.g.dart **/*.freezed.dart lib/l10n/* lib/core/failures/failure.dart'
      min_coverage: 0
      format_line_length: 80
      

      
      
    
   

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: |
        **/*.md
      modified_files_only: false

      
